### ISSUE TITLE
ERROR - useState()

### ISSUE THREAD

**Issue by Jasiostwor** [Jasiostwor/biblioteka#1]
@pawelprojext 
W plikach components/addBook/adBook.jsx i components/logoutButton/logutButton.jsx

Coś tutaj nie gra chyba nie wiem czy to wpływ na działanie aplikacji więc na razie Low prority task

![obraz](https://github.com/Jasiostwor/biblioteka/assets/70820147/2c774324-30bd-4aa5-8b9e-98e2d9227d07)

**Comment by pawelprojext** [comment]
zrobione :)
