### ISSUE TITLE
BUG - ikonki

### ISSUE THREAD

**Issue by Jasiostwor** [Jasiostwor/biblioteka#5]
VERY LOW PRIORITY

Jedna ikonka przy małych rozdzielczościach znika
Nie jest to wielkie niedociągnięcie ale jak będziecie się nudzić to można naprawić

![obraz](https://github.com/Jasiostwor/biblioteka/assets/70820147/4e7bc24e-bc45-43a6-90fa-ca2d5e50b7b4)

**Comment by pawelprojext** [comment]
Zrobione :)
